from .afm import AFM
from .deep_crossing import DeepCrossing
from .deepfm import DeepFM
from .dssm import DSSM
from .ffm import FFM
from .fm import FM
from .lr import LR
from .mlp import MLP
from .mmoe import MMOE
from .nfm import NFM
from .pnn import PNN
from .wide_and_deep import WideAndDeep
