from easyrec.models.afm import AFM
from easyrec.models.dcn import DCN
from easyrec.models.deep_crossing import DeepCrossing
from easyrec.models.deepfm import DeepFM
from easyrec.models.dssm import DSSM
from easyrec.models.ffm import FFM
from easyrec.models.fm import FM
from easyrec.models.fnn import FNN
from easyrec.models.lr import LR
from easyrec.models.mlp import MLP
from easyrec.models.mmoe import MMOE
from easyrec.models.neumf import NeuMF
from easyrec.models.nfm import NFM
from easyrec.models.pnn import PNN
from easyrec.models.wide_and_deep import WideAndDeep
