from easyrec.models import AFM
from easyrec.models import DSSM
from easyrec.models import DeepCrossing
from easyrec.models import DeepFM
from easyrec.models import FFM
from easyrec.models import FM
from easyrec.models import LR
from easyrec.models import MLP
from easyrec.models import MMOE
from easyrec.models import NFM
from easyrec.models import PNN
from easyrec.models import WideAndDeep
from easyrec.models import FNN
from easyrec.models import NeuMF
